const products = [
    {
        _id: 1,
        name: 'Mandala Text',
        image: '/images/1.png',
        description: 'A frame with mandala designed background along with "Mandala" as a text on it.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 10.99,
        countInStock: 10,
        rating: 3,
        numReviews: 4,
    },
    {
        _id: 2,
        name: 'Flowers Sketch',
        image: '/images/2.png',
        description: 'A frame with Flowers sketch on watercolor paper texture with watercolor brushes from Procreate.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 9.99,
        countInStock: 15,
        rating: 2.5,
        numReviews: 3,
    },
    {
        _id: 3,
        name: 'Easter Egg',
        image: '/images/3.png',
        description: 'Happy Easter with Furry Egg Illustration.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 15.99,
        countInStock: 13,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: 4,
        name: 'Smiley',
        image: '/images/4.png',
        description: 'A frame with Smiley Kiss illustration.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 8.99,
        countInStock: 5,
        rating: 4,
        numReviews: 13,
    },
    {
        _id: 5,
        name: 'Pikachu',
        image: '/images/5.png',
        description: 'A frame with Pikachu illustration.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 18.99,
        countInStock: 5,
        rating: 5,
        numReviews: 19,
    },
    {
        _id: 6,
        name: 'Orangy Fur',
        image: '/images/6.png',
        description: 'A frame with Oval Shapped Orange furry baby illustration',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 12.99,
        countInStock: 10,
        rating: 5,
        numReviews: 17,
    },
    {
        _id: 7,
        name: 'Butterfly',
        image: '/images/7.png',
        description: 'A frame with Butterfly illustration and text.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 11.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 20,
    },
    {
        _id: 8,
        name: 'Mandala',
        image: '/images/8.png',
        description: 'A frame with mandala design on colorful background.',
        brand: 'prakrutiXart',
        category: 'Frames',
        price: 14.99,
        countInStock: 10,
        rating: 3.5,
        numReviews: 5,
    },
]
export default products